[library]
[library.BmiDhsvm]
language = "c++"
library = "bmi_dhsvm"
header = "bmi_dhsvm.hxx"
entry_point = "BmiDhsvm"

[build]
undef_macros = []
define_macros = []
libraries = []
library_dirs = []
include_dirs = []
extra_compile_args = []

[package]
name = "bmi_dhsvm"
requirements = []

[info]
github_username = "pymt-lab"
package_author = "csdms"
package_author_email = "csdms@colorado.edu"
package_license = "MIT"
summary = ""

