{% set data = load_setup_py_data() %}

package:
  name: "pymt_cem"
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy 1.11.*
    - model_metadata
    - cem 
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - cem 

test:
  requires:
    - bmi-tester
    - model_metadata
  imports:
    - pymt_cem
  commands:
    - config_file=$(mmd-stage Cem . > MANIFEST && mmd-query Cem --var=run.config_file.path)
    - bmi-test pymt_cem.bmi:Cem --config-file=$config_file --manifest=MANIFEST -v
    - config_file=$(mmd-stage Waves . > MANIFEST && mmd-query Waves --var=run.config_file.path)
    - bmi-test pymt_cem.bmi:Waves --config-file=$config_file --manifest=MANIFEST -v

about:
  summary: Python package that wraps the cem BMI.
  home: https://github.com/mcflugen/pymt_cem
  license: MIT license
  license_file: LICENSE
  dev_url: https://github.com/mcflugen/pymt_cem
